### ISSUE TITLE
Volume change triggers NaN error using MPD player.

### ISSUE THREAD

**Issue by phbcanada** [fatg3erman/RompR#111]
When the player controller do_command_list is executed it does: player.status.cloneObject(s)
As a result, player.status.volume no longer exists.
I'm running mpd version 0.21.5 on raspberry pi 4. Rompr on Apache2, same machine.
The status object returned is:
```
Id: "19"
Last-Modified: "2012-07-12T11:19:56Z"
Pos: "18"
Time: "401"
audio: "44100:24:2"
bitrate: "320"
consume: "0"
duration: "400.848"
elapsed: "18.639"
file: "Pat Metheny Group/What's it All About/11. Round Midnight.mp3"
mixrampdb: "0.000000"
playlist: "2"
playlistlength: "19"
radioconsume: 0
radiomaster: ""
radiomode: ""
radioparam: ""
random: "0"
repeat: "0"
replay_gain_mode: "off"
single: "0"
song: "18"
songid: "19"
state: "pause"
time: "19:401"
```
Do I need to update to the latest mpd version?

**Comment by fatg3erman** [comment]
The variable 's' should contain the volume parameter, it is not being lost, it simply isn't there in the first place, so your mpd is not reporting it. I don't know why that would be.

I can't reproduce this. I'm running mpd 0.22, but this code is like 10 years old, I've never encountered a version of mpd that didn't return the volume. Some early versions could not adjust the volume if they were paused or stopped. Perhaps that's the issue?

What happens if you telnet to the mpd port on your Pi and type status? Is the volume returned there?

**Comment by kingbu** [comment]
MPD version 22.5 is buggy.
Better update to newest 22.6

Please see musicpd.org for releases issue.
;-)

**Comment by phbcanada** [comment]
telnet response:
```
OK MPD 0.21.4
status
repeat: 0
random: 0
single: 0
consume: 0
playlist: 5
playlistlength: 16
mixrampdb: 0.000000
state: stop
OK
```
Strange that "mpd --version" shows 0.21.5. I will try building and installing the latest version.

**Comment by phbcanada** [comment]
I discovered this: https://askubuntu.com/questions/383449/mpd-failed-to-read-mixer-for-my-alsa-device-no-such-mixer-control-pcm

So if I set mixer_control to "Headphone" in mpd.conf the volume shows up and seems to work fine. 
You can close this issue - unless you want to add some work around to deal with the missing volume info.
