### ISSUE TITLE
FR: Prefer higher quality formats when playing local music

### ISSUE THREAD

**Issue by jdheyburn** [fatg3erman/RompR#113]
Hey - firstly I _love_ this project, I've been playing around with it for a few days as my aggregator for my own music alongside Spotify. 

I rip my music in FLAC and then convert to mp3. I have `mopidy-local` set up to to read a directory containing all of these flacs and mp3s, and in rompr I can see these in the Local view of the File Browser tab:

![image](https://user-images.githubusercontent.com/34041368/114844718-f68c1280-9dd2-11eb-9d31-41df7fe9516f.png)

When I view these back in the Music Collection, the format is not specified - which is fine - but when I play it it will play the mp3 version.

![image](https://user-images.githubusercontent.com/34041368/114845274-8cc03880-9dd3-11eb-9f6e-37b098a4d8b0.png)

![image](https://user-images.githubusercontent.com/34041368/114845369-9cd81800-9dd3-11eb-9ce1-fa2486438e53.png)

I imagine rompr is doing the management of the Music Collection piece. Is it possible to have a setting to detect when there are multiple formats available for a track and depending on user preference, play one of them? Perhaps even something hierarchical (e.g. flac > ogg > mp3).

Hope that makes sense - thanks!

**Comment by fatg3erman** [comment]
I understand your problem, thanks for the good description. However, a fundamental design principle of Rompr is that the filenames and formats are not used at all when sorting the collection. In fact with the current database schema, what you ask is impossible.

However there is a solution. The reason Rompr is using the mp3 version is simply that Mopidy lists the tracks in alphabetical order. 'mp3' comes after 'flac' so the mp3 version overwrites the flac version in the database. To resolve this you need to change the order of the tracks so that Mopidy lists the mp3s first. You could put the mp3s in a subdirectory and leave the flac files where they are. You could adopt a file naming scheme that puts the mp3s first. 
You could even add Disc Number tags to everything so the flacs are on one disc and the mp3s are on another disc. Then both types of track will appear in the collection.

**Comment by jdheyburn** [comment]
Thanks for the detail @fatg3erman - I'll have a play around with the sorting. It's not a deal breaker, I'm just glad to have everything centralised finally!

**Comment by fatg3erman** [comment]
Actually I think I meant put the flac files in a subdirectory and leave the mp3s where they are. One way or the other will work.
