### ISSUE TITLE
FR: Better multiple artist submission to online databases

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#12]
HI

One issue I have with online database queries is that the album artists with multiple artists return nothing. By the nature of query, this makes sense but it would be nice if we could find a better way to get this going.

Lets say I have an album artist like "Sainkho Namtchylak & Ned Rothenberg", now for the most web services this returns nothing. Ideally Rompr could search for Sainko and Ned separately and somehow display them separately? 

Even the Wikipeda one is a bit better because it returns results for the first artist in the query.

thanks

**Comment by fatg3erman** [comment]
This is actually very hard to do properly, I have tried it in the past and the results were inconsistent (not all languages use '&', for example).

This is actually better sorted by tagging your local files better. While some taggers will add the artist with an '&', as you have, many will actually add multiple Artist tags to the file. This is handled well by both MPD and Mopidy and means Rompr gets separate information about all the artists and I don't have to make guesses. When this happens Rompr will display an artist chooser above the information panel, allowing you to select an artist.

I think Musicbrainz Picard is one such tagger, and think Beets also does this.

**Comment by gerroon** [comment]
Hi

Yeah I realize that it is a hard issue. But the thing is that sometime it is a a huge problem to go back and retag all your libraries especially if one has been collectiong musiv all her life.. I have been using Picard for quite sometime and some Musicbrainz entries are all mixed bag as well. 

Also the issue is that it is impossible to know what  application one might use to listen their music in their future, therefor hard to guard againts such issues in the current time dimension.

**Comment by fatg3erman** [comment]
The thing is that in some cases, the artist with the & is the one you want. Take 'Jah Wobble & The English Roots Band', 'Rocket Juice & the Moon', 'Belle & Sebastian'. Just because a service returns no information does not mean the artist queried for was not correct. 

Then suppose I decide to split on 'and' or '&'  but it's in French - 'Jean et Henri', or German, or Italian, or.. Chinese.

I know tagging all your files is a hassle, but I have spent a lot of time in the past trying to make this suggestion work, and there's no adequate solution. Doing what you suggest generates as many 'false positives' as the current method generates negatives.

I'll leave this open as I may return to it.

**Comment by gerroon** [comment]
@fatg3erman 

You make a good case, I wont deny it. The reason I open the bug to create a discourse about this issue.  I am not a dev so I can help with this but I will try to come up with further ideas. Maybe someone else can chime in later as well.

**Comment by fatg3erman** [comment]
To be honest, the technical aspects of coding it to make it work are quite interesting, and for that reason it's something I'll probably look at in due course.
