### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by oupala** [fatg3erman/RompR#120]
When enabling Content Security Policy on the webserver that serves RompR, `unsafe-inline` and `unsafe-eval` have to be enabled as RompR is including some js and some css in the html.

Do you think it could be possible to remove this requirement, hence making RompR mose secure and reliable?

`unsafe-inline` and `unsafe-eval` are obviously a bad habits and they could be easily avoided by moving css and js code un css and js files.

More informations on demande if you need some.

**Comment by fatg3erman** [comment]
Rompr has never been designed with security in mind - I do not advise using it on a server that can be accessed from the internet. 

The inline js and css are practical ways of working around browset security in order to provide useful functionality, so I don’t think it’s piossible to do it another way.

**Comment by oupala** [comment]
Every piece of software should be designed with security in mind. You never know if something that is not exposed on the internet will be exposed on the internet, one day, by mistake.

I'm not sure of the advantages of using inline css and js. But it would be a very good thing to add this improvement as a goal for a futur milestone.

In the meantime, altough not secured, RompR is still a very good piece of software.
