### ISSUE TITLE
FR: Show only ones that return positve query

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#13]
Hi

One thing that might make sense to display the icons of the web services that actually return something that way the user will know what to click, at the the moment, I just click from left to right to see what came up. And sometimes half of those services cant return something. 

Would not make sense to maybe turn the icons of the empy/non existing searches to gray or hide them? That way the user wont go for clicking to that service that returns nothing, unless wants to checxk it out anyways.

**Comment by fatg3erman** [comment]
While you're right that it would be better for the user, the panels (except Last.FM and sometimes Musicbrainz) don't start populating until you click them. Otherwise Rompr would create a storm of web requests every time you play a track, which would likely lead to me getting banned from some of those APIs, so I'm not going to change that.

**Comment by gerroon** [comment]
@fatg3erman 

OK that makes sense. Let the bug roam around for a while then, you never know :)
