### ISSUE TITLE
Having RompR Backend Daemon running on background - sound like spyware

### ISSUE THREAD

**Issue by danilw** [fatg3erman/RompR#144]
**Main reason why I was using RompR for many years** - its minimalistic and require nothing else than apache and use only php and mpd to play audio.

Now since https://github.com/fatg3erman/RompR/releases/tag/2.00

> This version introduces the RompR Backend Daemon which replaces romonitor and is now a requirement. 

**Maybe im not understanding something** - but running php-code demon that run all the time on background and have access to the internet and "do something".
Even if its codebase is opensource - code is huge with lots of includes and using other scripts, I mean code complexity complex enough to "hide something".

**I understand - it may be just "easy way to implement some complex features"** that before was implemented as "bad php trick" and "no spyware intention".
But fact that it "run on background" and use internet - does not look "safe" for me.

### Solution I see:

**Two version of RompR:**
 - RompR with no features that require "background activity"
 - RompR with full features and "background php-daemon"

**Comment by fatg3erman** [comment]
Oh come on, this is ridiculous. The daemon exists because it makes rompr better and easier to maintain. If you don't like it then don't use it but it is not changing. You realise that MPD and Mopidy are both daemons that run all the time and have access to the internet, rught? Rompr is the same as that. Why are you happy to run MPD but you come here and accuse me of not being safe?
