### ISSUE TITLE
Mopidy - error adding non-local tracks via File Browser

### ISSUE THREAD

**Issue by leinaht** [fatg3erman/RompR#150]
I can add items from Mixcloud, Soundcloud, etc using ncmpcpp and Mopidy frontends like Iris, but when adding them from RompR I get a "Player error: {add} directory or file not found" error. From the debug logs it looks like RompR is prepending "local:track:" to the URI, perhaps unnecessarily? 
[debug.log](https://github.com/fatg3erman/RompR/files/12215875/debug.log)

**Comment by fatg3erman** [comment]
It's this : Translating Track Uris from mpd to mopidy

This indicates you used MPD to create your Music Collection. Unfortunately in that configuration you can't add tracks from non-local URIs to Mopidy, because it would make no sense in MPD.

If you want to use mixed player types then you should create your collection using Mopidy. To do this you'll need to delete your current collection file (prefs/collection.sq3 if you're using SQLite) and your prefs file (prefs/prefs.var) and rebuilf your collection using your Mopidy player.

**Comment by fatg3erman** [comment]
In fact, thinking about it, this means that if you created your collection using MPD, the file browser won't work on a Mopidy player at all. That's just something that's probably never going to be fixable given the differences in the URI schemes used by each player, I've no way to tell where the URI has come from.

**Comment by leinaht** [comment]
That was it, thank you!
