### ISSUE TITLE
Request for clarification: release 2.09

### ISSUE THREAD

**Issue by Marcool04** [fatg3erman/RompR#156]
Hi there,

I'm sorry to open an issue for this (and feel free to close it instantly), but I am the maintainer of the RompR package on the Arch linux User repository https://aur.archlinux.org/packages/rompr and I was wondering if possibly something got mixed up in the 2.09 release? For one thing, I received two notifications from github that there had been a 2.09 release. Then, when I updated the package, one user found that the checksums for the zip file were wrong. When I downloaded the zipfile again, the checksum had indeed changed, seemingly without any note anywhere of it.

I just wanted to see if you could give me more information about what went on here. Did you possibly reupload a different zip file under the 2.09 release? (if so, I wasn't even aware that was possible, but maybe it is somehow...)

Thanks for your work on RompR and for any insight you could give into this.
Regards,
Mark.

**Comment by fatg3erman** [comment]
Hi, yes apologies for the mix up. I did indeed upload 2 versions of 2.09. I thought I'd done it quickly enough that nobody would notice. (I actually deleted the first one and then made another).

There is now a 2.10 release anyway, since I discovered another mess-up. Thanks for maintaining the AUR package. I'll try to make sure this doesn't happen again :)

**Comment by Marcool04** [comment]
No problem man. Thanks for explaining. Keep up the good work 👍️
