### ISSUE TITLE
Question about Music Collection and Subsonic

### ISSUE THREAD

**Issue by kindlydodo** [fatg3erman/RompR#161]
Big thanks to this great pice of software!

I use mopidy with rompr. Also ive installed mopidy-Subidy for getting my music from my subsonic server ( https://github.com/Prior99/mopidy-subidy ).

On the Search and File browser screen in romper, i got access to my subsonic music.

Now I tried to collect that on the rompr Music Collection screen, to get all of the features romper offering. But when i update the music collection, there are no files found

Did I misunderstand someting here?

My expectations were, rompr will index all my files from subsonic in the music collection.

**Comment by fatg3erman** [comment]
Because every Mopidy backend works differently I have to add specific support for each one in order to make it compatible with the Music Collection. I don't have support for Subsonic because I don't have any way to test it.

it wouldn't be very difficult to add, if you can work with me and provide a few basic pieces of information by running a few commands on your setup. Let me know if you want to do that.

**Comment by kindlydodo** [comment]
Sure i would! Thank you!

**Comment by fatg3erman** [comment]
OK so I actually managed to get this basically working by installing airsonic.
I've attached a beta release of 2.15 with Subsonic support, please try it and let me know who you get on. Please don't redistribute this version.
Some things to note:
Building the collection from Subsonic will be very slow because Mopidy has to query subsonic for every single album separately.
Subsonic does not seem to use Album Artist tags. This might cause some issues with sorting albums in your Collection.
[rompr-2.15-beta.zip](https://github.com/fatg3erman/RompR/files/14970033/rompr-2.15-beta.zip)

**Comment by kindlydodo** [comment]
OK
I installed it by copy the files into the working rompr dir. Restart all the services and rompr starts. 

On the "Music Collection Screen", I left the default search setting (Artist / Entire Collection no option checkbox checked). When starting "update music collection now", It doesn't find anything. it's just like before, nothing has changed. I then tried again whit different Search settings, same behavior.

Nothing special in the logs.

```
192.168.1.104 - - [15/Apr/2024:08:38:37 +0200] "POST /api/player/ HTTP/1.1" 200 378 "http://192.168.1.62/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
192.168.1.104 - - [15/Apr/2024:08:38:37 +0200] "GET /api/collection/?rebuild=yes&_=1713162892341 HTTP/1.1" 200 40 "http://192.168.1.62/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
192.168.1.104 - - [15/Apr/2024:08:38:37 +0200] "GET /api/dirbrowser/ HTTP/1.1" 200 294 "http://192.168.1.62/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
192.168.1.104 - - [15/Apr/2024:08:38:37 +0200] "GET /utils/checkupdateprogress.php HTTP/1.1" 200 57 "http://192.168.1.62/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
192.168.1.104 - - [15/Apr/2024:08:38:38 +0200] "GET /utils/checkupdateprogress.php HTTP/1.1" 200 58 "http://192.168.1.62/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
192.168.1.104 - - [15/Apr/2024:08:38:39 +0200] "GET /api/collection/?item=aartistroot&_=1713162892342 HTTP/1.1" 200 293 "http://192.168.1.62/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
192.168.1.104 - - [15/Apr/2024:08:38:39 +0200] "GET /api/collection/?item=zartistroot HTTP/1.1" 200 195 "http://192.168.1.62/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
```

What I should have said is that i'm using navidrome as my subsonic server, maybe this is different?

Greats

**Comment by fatg3erman** [comment]
Have you definitely gone to the settings and enabled "Subsonic" under "Build Music Collection From"?

**Comment by kindlydodo** [comment]
No i don't. I wasn't aware of that setting. After I've enabled it "Build Music Collection From" have worked! Now i have my subsonic Music in the Music Collection. Until now, no problem. I will test this out this week and give you feedback.

Sidenote:
My Navidrome Subsonic Server has 216 artists and 1716 tracks. The server have 32gb ram, and AMD Ryzen 5 5600G. Build Music Collection took about 1 min.

**Comment by kindlydodo** [comment]
I did my tests and just use Rompr as always and so far i did not encounter any problems.

Thank you!

**Comment by fatg3erman** [comment]
Nice. Thanks for the update. I'll make a new release at some point.
