### ISSUE TITLE
FR: Podcasts: Set refresh other than manual on import

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#39]
Hi

I was trying to figure out why my podcasts were no updating, then I went into settings and I saw that all were set to manual. This can be a hassle like people like me with hundreds of podcasts, I mean trying to edit all this stuff afterwards. It would be nice if there is a way to set a general update frequency that can be applied to all podcasts during import so at least one can choose a rough refresh time for all.

Maybe there is a way to set a cron job? I do not mind doing this through my system's cron.

**Comment by fatg3erman** [comment]
Podcasts are supposed to set a refresh period in their feed - and Rompr will honor this if it is there - but many simply omit this value, which is annoying I agree. I default to Manual in that case. I can certainly add an option to change the default setting.

If you'd like to update your podcasts quickly, if you're comfortable with using something like PHPMyAdmin you can edit your database directly - edit the table Podcasttable and set the value of RefreshOption for every entry.

4 = Monthly
3 = Weekly
2 = Daily
1 = Hourly
0 = Manual

You could do this with the folling SQL statement:

    UPDATE Podcasttable SET RefreshOption = 3

would set every podcast to update weekly

You can use a cron job to refresh your podcasts  - though I haven't tried this and it will only work for podcasts that are not set to Manual, so it doesn't help this particular problem but I mention it because it is possible.

    curl  http://address.of.rompr/includes/podcasts.php?rebuild=1&checkrefresh=1 > /dev/null

**Comment by gerroon** [comment]
I did not know that update value was an inherint variable.  I can try intjecting that to opml next time.

Thanks I will try the phpmyadmin set up I have here.

**Comment by fatg3erman** [comment]
It's not in the OPML, it's in the podcast's feed. The OPML simply lists a bunch of feeds. There's no way to edit the feed.

**Comment by fatg3erman** [comment]
By the way though, if you have 200 Podcasts you added at the same time via the OPM importer, it has just occurred to me that they will all update simultaneously. This will put a big load on your server while it happens, so I would advice against doing it daily unless you do it overnight with a cron job.

**Comment by gerroon** [comment]
I set to daily and I will set a cron job. I have alot of podcsats but only small percent really updates daily.

**Comment by fatg3erman** [comment]
Even if they don't update, Rompr still has to retrieve each feed and parse it, so it makes no difference to the system load.

**Comment by gerroon** [comment]
I see, that makes sense. It should be ok for my system, I am the only user of this. I will let you know how it goes.

**Comment by gerroon** [comment]
Btw since I am doing tests with podcasts, how can I mass tag them as listened with slq commands ? and Maybe deleye all dusbcriptions if I need them?

**Comment by fatg3erman** [comment]
To mark ALL your podcast episodes as listened

    UPDATE PodcastTracktable SET Listened = 1;

To delete all your podcasts

    TRUNCATE TABLE PodcastTracktable;
    TRUNCATE TABLE Podcasttable;

**Comment by gerroon** [comment]
Thanks

**Comment by fatg3erman** [comment]
Addressed in 1.19
