### ISSUE TITLE
Rompr adds an extra dash to Mpd playlist info lines

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#53]
Hi

I am puzzled about this situation. My playlist in the .m3u file does not have dashes, and Mpd does not show the dashes either (in ncmpcpp) but Rompr is showing with dashes 

That playlist had dashes before but I edited them out, so they do not look ugly, somehow they survive in Rompr :(  Those dashes are still there when added to the current play queue but not in ncmpcpp after added by Rompr :) 

The issue is that Rompr shows them with dashes in the song details at the top which I assume also submits to the online queries that way like below

```GETALBUMCOVER         Trying Google for - 100% Jazz```

**from .m3u file**
```
#EXTM3U
#EXTINF:0,DeepTechnoFM
http://centauri.shoutca.st:8154
#EXTINF:0,Proton Radio
http://protonradio.com:8000/schedule

```

**from ncmpcpp playlist editor**
![selection_030](https://user-images.githubusercontent.com/8519469/42852886-b1582050-89f8-11e8-9b7f-6f5a903393fe.png)

**from ncmpcpp play window details** (no dashes)
![selection_033](https://user-images.githubusercontent.com/8519469/42853064-b4b268ae-89f9-11e8-831f-d3de2264019b.png)

**from Rompr load  playlist window** (expanded the playlist)
![selection_031](https://user-images.githubusercontent.com/8519469/42852908-ce2e1dec-89f8-11e8-915a-51b2e53ecc75.png)

**from Rompr play window** (dashes are there)
![selection_032](https://user-images.githubusercontent.com/8519469/42853027-780c03ce-89f9-11e8-9384-1f85d334e073.png)

**Comment by fatg3erman** [comment]
The problem here is that I’m expecting tracks in a playlist to have an Artist and an Album, which I then display as

Artist - Album

What you have here is the unusual situation where you have effectively an album with no artist. The artist is therefore empty, hence the dash. 

A playlist of radio stations is a real edge case, I’d never even thought of that. 

As for the online stuff, it’s the same, the concept of an album without an artist makes no sense, so the code doesn’t handle it. The dash won’t make any difference there anyhow.

**Comment by gerroon** [comment]
Hi

What you are saying makes sense but like you stated online streams seems to be an edge case. 

I use Vlc or Clementine to maintain online radio playlist and that is how they save the playlist, given that it does not make sense to have album in stream radio definition.

If Rompr can handle the urls that seems like an online stream, that  would be great, if not we just live with it :)

**Comment by fatg3erman** [comment]
There's nothing at all wrong with the playlist, it's just that I never expected to encounter one like that :) I'm sure it's an easy fix, when I have time to look at it.

**Comment by gerroon** [comment]
Thanks man.

I never was aware of the issue until you stated the obvious. All other apps never shown the issue in this regard.

**Comment by fatg3erman** [comment]
I can't reproduce this issue with the M3U fragment you have provided.

M first comment wasn't correct, having now looked at the code. I do handle that edge case there. But you say the M3U did originally have dashes in it, so in fact that's what the problem was. You've played the stations once, with the dashes and rompr has stored the names - with the dashes - in the database.

Editing the M3U will now have no effect since rompr stores radio station names in the database permanently because - except in this one edge case - MPD usually gives it no information to set the station name until the stream starts to play. (Compare to Mopidy which handles radio streams superbly and provides all the metadata a player needs)

If you really want to clear this up then your only hope is to find the streams in your database and edit the names by hand. Look in RadioStationtable AND RadioTracktable - they will probably be in both tables.

**Comment by gerroon** [comment]
Ok so the issue is that Rompr does not actually update the database regarding the radio stations. I will mess witht he database solution and let you know.

As far as Mopidy goes, I want to use it more often but I find that its playback hit and miss with radio stations when changing tracks. Basically when I change the track (prev/next), it plays the previously playing tack/station. I do not, it is very frustrating to me, thaty is one reason I d onot use Mopidy that often. This is also issue it podcast streaming. 


Not sure if you have this playback issue with Mopidy yourself, but that is why I was happy to find Rompr because I can actually play my podcasts through Mpd not Mopidy without going nuts while trying to stream.

**Comment by fatg3erman** [comment]
Well, once it has a name for a radio station there is no need to update the database. In this one specific case you provided it with a playlist with incorrect names. That’s not really rompr’s problem. Normally it gets the names from the station metadata as provided by mpd or mopidy. They never change so why would I ever update them. I’m not going to change that as it defeats the object of storing the names in the first place.

Yes Mopidy does have some issues skipping tracks with streams. It’s a low level bug in gstreamer. There is a fix of sorts out there somewhere but mopidy development appears to have stalled.

**Comment by gerroon** [comment]
Understandable, the logic of the station name sounds solid. I will edit my database.

Is the station name tied to playlist position, station url or some uniq id once added etc?

Yeah Mopidy does not seem to get updates, not sure why the development would stall, it is not like nobody is using it :(

**Comment by fatg3erman** [comment]
The station name is tied to the url, since, for stations in the current playlist, the url is the only info mpd gives me.
