### ISSUE TITLE
Raspian MYSQL doeant support InnoDB engine

### ISSUE THREAD

**Issue by TheBodger** [fatg3erman/RompR#57]
I tried to install the latest rompr version onto the latest Raspian, with MYSQL, following the linux instructions. The setup page failed with "BADGERS", and that a table .... ERROR 1214 (HY000): The used table type doesn't support FULLTEXT indexes
I changed the Engine param for all tables in specifics.php in the mysql folder from Innodb to MyISAM and reloaded the page. This cured the problem. 

Server version: 5.5.60-0+deb8u1 (Raspbian)
PHP 5.6.36-0+deb8u1 (cli) (built: Jun 26 2018 22:52:39)

Not sure if this is the correct way to raise a bug/solution for a particuar Os/MySQL version

thanks

**Comment by fatg3erman** [comment]
That’s very concerning if distributions are not supporting certain MySQL features. I’m not sure if some of the other features in rompr work with MyISAM either.

**Comment by fatg3erman** [comment]
OK having done some research, your version of MySQL is outdated. InnoDB doesn't support FULLTEXT indexing in version 5.5. Most distros are now providing 5.7, and the current release version of MySQL is 8.0, so Raspian could do with being updated.

My suggestion, to prevent future Rompr upgrades from breaking because you're using the wrong table type, is to simply not use the FULLTEXT index on those tables. To be honest I'm not certain it has much effect at speeding things up, I'll probably just remove it.

So, delete your rompr database and edit your specifics.php so the offending items now look like

	if (generic_sql_query("CREATE TABLE IF NOT EXISTS RadioTracktable(".
		"Trackindex INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE, ".
		"Stationindex INT UNSIGNED REFERENCES RadioStationtable(Stationindex), ".
		"TrackUri TEXT, ".
		"PrettyStream TEXT, ".
		"PRIMARY KEY (Trackindex)) ENGINE=InnoDB", true))
	{
		debuglog("  RadioTracktable OK","MYSQL_CONNECT");
	} else {
		$err = $mysqlc->errorInfo()[2];
		return array(false, "Error While Checking RadioTracktable : ".$err);
	}
	
	if (generic_sql_query("CREATE TABLE IF NOT EXISTS WishlistSourcetable(".
		"Sourceindex INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE, ".
		"SourceName VARCHAR(255), ".
		"SourceImage VARCHAR(255), ".
		"SourceUri TEXT, ".
		"PRIMARY KEY (Sourceindex)) ENGINE=InnoDB", true))
	{
		debuglog("  WishlistSourcetable OK","MYSQL_CONNECT");

**Comment by TheBodger** [comment]
Thanks Mark

 

I will make the changes

**Comment by TheBodger** [comment]
Hi

 

That worked a treat

 

thanks
