### ISSUE TITLE
last.fm api returning invalid images

### ISSUE THREAD

**Issue by CultofRobots** [fatg3erman/RompR#79]
last.fm made changes to their api (see here: https://getsatisfaction.com/lastfm/topics/api-announcement-dac8oefw5vrxq). As a result, rompr only returns stub images. (ex. https://lastfm-img2.akamaized.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png)

**Comment by fatg3erman** [comment]
Yeah. Thanks, I'm aware of that. Last.FM is going down the toilet. 9 years I've been using that API and they change it with no notice. Then they link to terms of use which have changed (with no notice) since I agreed to them. 

I guess I'll have to remove the artist images from last.fm pages, which is a real shame. I think this is the beginning of the end.

**Comment by fatg3erman** [comment]
The Last.FM panel will now try to use other sources of images, but it isn't always successful in finding them.

**Comment by erykpham** [comment]
hey! you are using it free, don't complain

**Comment by fatg3erman** [comment]
Are you searching for closed bug reports to spam? I'm well aware I'm using it for free. I'm also well aware that no company gives anything away for free unless they think they have something to gain by doing so. So don't come here berating me for complaining that a published API changed its terms of operation WITHOUT NOTICE. Don't  have a go at me for expecting an agreement to be upheld. Don't you dare judge me for expecting a company to uphold an agreement it forced me to sign up to. Just because I'm getting it for free does not mean I agree to be fucked over.
