### ISSUE TITLE
use mpc sticker for rating

### ISSUE THREAD

**Issue by internethering** [fatg3erman/RompR#82]
hey. I'm using normaly cantata and have rated my music with this tool. It saves the rating in the sticker database. It would be nice, If rompr could read/write this database.

example mpc commands:

mpc sticker "`mpc -f %file% current`" get rating
mpc sticker "`mpc -f %file% current`" set rating 0-10

**Comment by fatg3erman** [comment]
I did look at this a while ago. The trouble is there is no defined way of storing data in the MPD sticker database. So I could write something that would work with Cantata but it might not work with a different MPD client.

I'm not against the idea, I'm all in favour of working together, but it's hard to figure out the best way to do it. Do you know of any other MPD clients that use the sticker database to store ratings?

**Comment by jcorporation** [comment]
myMPD uses the MPD sticker database to store ratings. 

https://github.com/jcorporation/myMPD/wiki/Sticker

**Comment by fatg3erman** [comment]
And there's the nub of the problem. That's two different clients using two completely different schemes to store data. That's why writing an importer would be fraught with difficulties and would fail more often than it worked.

**Comment by fatg3erman** [comment]
I've added a plugin in version 1.42 to import ratings from the sticker database into Rompr.

As Cantata is no longer under active development, I won't be adding any functionality to write to the sticker database, because it's pointless putting in effort to support something that is now effectively obsolete.

The importer will work with stickers created using Cantata, which uses a sticker called 'rating' with a value between 1 and 10. Since I've no way of knowing which client was used to create the stickers, if you have used a different client, anything could happen.
