### ISSUE TITLE
FR: Option to disable Podcast refresh when page loads

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#85]
Hi

It seems like refreshing podcast sems to slow things done when the page is loaded  the first time. It would be nice if there is an option to disable the podcast refreshes if the ui is opened/loaded in a non podcast page.

thanks

**Comment by fatg3erman** [comment]
I was wondering what it was that kept slowing the page load down and I think you're spot on. Nice find. It shouldn't be updating the podcasts at that point anyway so it's obviously a bug. Thanks.

**Comment by fatg3erman** [comment]
OK so there were multiple problems here with several asynchronous things happening simultaneously and putting a big load on the web server. I didn't notice it on my dev machine because it's a beast of a machine :) I think I have a fix, basically now it waits 30 seconds before doing the initial refresh of the podcasts, and I've made sure not to activate another update trigger until that first one has completed. It'll be in the next release.

**Comment by gerroon** [comment]
Hi

Thanks for the update. Is this going to be in anytime soon?  I can switch to the dev branch.


The other issue I see with refresh how late the "stars" show up in the ui. It seems like it takes a while until they show up and they are the last one to show up. Not sure if it is related or gives any clue to what is going on.

thanks

**Comment by fatg3erman** [comment]
*Everything* will take a long time while the page is loading, especially if you are subscribed to a lot of podcasts. I may look at some better ways to stagger the refresh of podcasts but the change I've put in will help.

It's on the dev branch now but the usual warnings apply - the dev branch is currently even more unstable than usual and the current version will make changes to your database that *cannot be undone and are not compatible with the release version*.  In other words if you switch to the dev branch you *cannot go back to the release branch* and I cannot guarantee it won't trash your database.

**Comment by fatg3erman** [comment]
Will be in 1.41
