### ISSUE TITLE
selecting genre or artist in music everywhere only returns first 100 entries

### ISSUE THREAD

**Issue by tkgafs** [fatg3erman/RompR#87]
[rompr.log](https://github.com/fatg3erman/RompR/files/4247614/rompr.log)

I am using Mopidy 3.0.1 on Ubuntu server 19.10 with the Mopidy-Local and Mopidy-MPD extensions and using your rompr code version 1.40

I only use local files and do not use spotify last.fm etc etc

If I use the Music From Everywhere Genre or Artist search

it only appears to return 100 entries each time, from which it then seems to select the 5 items to place in the playqueue

consequently it tends to play similar tracks each time it is run

to be fair I have never left it to play all 100 tracks to see what happens next.

I have attached a logfile showing this behaviour

I have browsed the code but cannot find anywhere where this limit is applied 

mopidy docs have this config setting

core/max_tracklist_length

    Max length of the tracklist. Defaults to 10000.

    The original MPD server only supports 10000 tracks in the tracklist. Some MPD clients will crash if this limit is exceeded

but obviously this is far in excess of the 100 tracks which are returned

any pointers to where problem occurs would be most helpful

**Comment by tkgafs** [comment]
not sure if it helps or not but I have noticed that if I use Advanced search with the option search only in music collection turned on I get more than 100 tracks returned

if the option is off the search seems to stop at 100 tracks

see attached pics

![MusicCollectionOff](https://user-images.githubusercontent.com/1531083/75391876-d5bce100-58e2-11ea-884a-03396cf36009.jpg)
![MusicCollectionOn](https://user-images.githubusercontent.com/1531083/75391897-dbb2c200-58e2-11ea-8120-b0889651cb87.jpg)

**Comment by fatg3erman** [comment]
That clearly means that the problem is that Mopidy's search only returns 100 tracks. In the source for mopidy-local there is a field called 'limit' that defaults to 100. There doesn't appear to be a way to change this without modifying the code.

If you're only using local tracks then you might find MPD suits you better.

**Comment by tkgafs** [comment]
Had rather guessed thats where the fault/limitation would be.

I had thought about using MPD but as far as i could tell, it did now appear to be able to drive a local soundcard and instead sent all the music to the client device, which is not what I need. 

What puzzled me was that I could not get your code to work until I installed mopidy-mpd extension I had expected it to work directly with mopidy.

As I said its all running on a headless ubuntu server that I couldnt get Kodi to start on, and your client's personal radios seemed to be the nearest client to my needs, and I've pretty much got it working the way I like to listen to music in my workshop.

Not used PHP or javascript much before so its been a struggle to work out how some of it works but my superfical amendments give me 90% of the functionality I was looking for. If I want to play a genre or artist randomly I still need to edit metadatafunctions sql select statement, until i can understand how parameter passing works !!

thanks again for a great chuck of code

**Comment by fatg3erman** [comment]
No, MPD outputs to a sound card exactly like Mopidy does. Or rather, Mopidy does it like MPD does, since Mopidy is just an MPD clone that also plays Spotify. (In fact MPD supports multiple simultaneous outputs in a way that Mopidy can only dream of.) If you just want local file playback, MPD is smaller, faster, more stable, and you can update your local music directly from Rompr without needing to use the additional 'mopidy local scan' step.

mopidy-mpd provides a client interface that mimics MPD's client interface. Since Rompr is intended to work with Mopidy and MPD it makes sense to use the same interface for both.

**Comment by tkgafs** [comment]
In that case I'll have another look, the stuff I read seemed to imply it didnt drive a local soundcard

**Comment by fatg3erman** [comment]
Added new options in 1.41 to use the database for this.
