### ISSUE TITLE
Last fm sync stalls after 2h

### ISSUE THREAD

**Issue by uriel1998** [fatg3erman/RompR#92]
I have a *large* music library, and I've been trying to get the last.fm playcount importer function to work... but it apparently stalls out after an hour or two (the estimated time to completion from the start is 4 hours).  Do I need to tweak a setting in php.ini to let it keep going, or something else? 

Thanks for any guidance you can give!

**Comment by fatg3erman** [comment]
It's very hard to debug this because a debug trace of that for 2 hours will crash your browser, so this will need some thought.

4 hours actually isn't very long, it's not unusual for that importer to take 24 hours or more. That said, it is usually quite good at estimating the time.

When you say it 'stalls', what exactly do you mean? How long have you left it? Last.FM will start to throttle you at some point and it might simply be that the code is waiting for a timeout to expire before continuing.

**Comment by uriel1998** [comment]
> When you say it 'stalls', what exactly do you mean? How long have you
> left it? Last.FM will start to throttle you at some point and it
> might simply be that the code is waiting for a timeout to expire
> before continuing.
> 

That may very well be it; I've usually just woken up the next morning,
seen that it hasn't moved in a while, and kill the browser window.
I'll give it a longer shot.

**Comment by fatg3erman** [comment]
I think I have actually found this bug!

Should be fixed in the next release.
